name: Docker Image CI

on:
    push:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        # steps:
        # - uses: actions/checkout@v3
        # - name: Build the Docker image
        #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ozan6825/wa-api
